# Generated by Django 5.1.5 on 2025-04-02 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date'], name='Discussion__date_49b7c1_idx'),
        ),
    ]
