# Generated by Django 5.1.5 on 2025-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_answers_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
